[package]
name = "abi_stable"
version = "0.9.1"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition="2018"
license = "MIT/Apache-2.0"
description = "For doing Rust-to-Rust ffi,writing libraries loaded at program startup."
documentation = "https://docs.rs/abi_stable/"
readme="../readme.md"
keywords = ["ffi","data-structures"]
categories = ["data-structures","rust-patterns"]
repository = "https://github.com/rodrimati1992/abi_stable_crates/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../readme.md", 
    "../APACHE_license", 
    "../MIT_license"
]

[badges]
travis-ci = { repository =  "rodrimati1992/abi_stable_crates/" }

[features]
default = ["channels","serde_json"]

rust_1_42=[]

# Enables stuff that requires const generics,use this once const generics are stabilized.
const_params=[]

# Enables all nightly features.
all_nightly=[
    "nightly_const_params",
]

# Enables stuff that requires const generics(in nightly Rust).
nightly_const_params=[]

# Test features,only used internally.
testing=[]
only_new_tests=["testing"]
sabi_trait_examples=[]
nonexhaustive_examples=[]

channels=["crossbeam-channel"]


[dependencies]
abi_stable_derive= {version="0.9.0",path="../abi_stable_derive"}
abi_stable_shared= {version="0.9.0",path="../abi_stable_shared"}
serde          = { version = "1.0.117", features = ["derive"] }
repr_offset = { version = "0.1.1", default_features = false }
serde_derive   = "1.0.117"
libloading     = "0.6.4"
parking_lot    = "0.11.0"
lock_api       = "0.4.1"
generational-arena = "0.2.8"
crossbeam-channel = { version = "0.5.0", optional = true }
serde_json = { version = "1.0.59", features = ["raw_value"], optional = true }

[dependencies.core_extensions]
default_features=false
features=["std"]
version= "0.1.18"

[dev-dependencies]
bincode = "1.3.1"
crossbeam-utils = "0.8.0"
serde_json = { version = "1.0.59", features = ["raw_value"] }
rand = "0.7.3"
criterion = "0.3.3"
hashbrown = "0.9.1"
fnv = "1.0.7"


[build-dependencies]
rustc_version = "0.2.3"